include: package:all_lint_rules_community/all.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'test/.test_coverage.dart'
    - 'bin/cache/**'
    - 'lib/generated_plugin_registrant.dart'
    - '**/l10n/gen/**'

  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    # Otherwise cause the import of all_lint_rules to warn because of some rules conflicts.
    # We explicitly enabled even conflicting rules and are fixing the conflict
    # in this file
    included_file_warning: ignore

linter:
  rules:
    # disabling rules that are incompatible with others
    always_specify_types: false
    avoid_final_parameters: false
    prefer_relative_imports: false
    prefer_double_quotes: false
    unnecessary_final: false

    # disable unnecessary rules / rules that reduce the readability of the code
    lines_longer_than_80_chars: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    diagnostic_describe_all_properties: false
    # TOOD(ods-team): remove this rule ultimately (we want everything to be public)
    public_member_api_docs: false
    prefer_final_parameters: false
    avoid_classes_with_only_static_members: false
    avoid_types_on_closure_parameters: false
    comment_references: false
